<?php

namespace Ais\HariBundle\Repository;

/**
 * HariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HariRepository extends \Doctrine\ORM\EntityRepository
{
}
